/**
 * AUTO-GENERATED by scripts/generate-openapi-routes.ts — do not edit by hand.
 * Regenerate: npm run openapi:generate
 */
import type { ScannedRouteOperation } from "@/lib/openapi/route-scan";

export const OPENAPI_ROUTE_INVENTORY: ScannedRouteOperation[] = [
  {
    "method": "delete",
    "path": "/api/v1/apps/{clientId}",
    "sourceFile": "apps/[id]/route.ts",
    "excluded": false
  },
  {
    "method": "delete",
    "path": "/api/v1/apps/{clientId}/admins",
    "sourceFile": "apps/[id]/admins/route.ts",
    "excluded": false
  },
  {
    "method": "delete",
    "path": "/api/v1/apps/{clientId}/billing/stripe",
    "sourceFile": "apps/[id]/billing/stripe/route.ts",
    "excluded": false
  },
  {
    "method": "delete",
    "path": "/api/v1/apps/{clientId}/discovery-profiles/{profileId}",
    "sourceFile": "apps/[id]/discovery-profiles/[profileId]/route.ts",
    "excluded": false
  },
  {
    "method": "delete",
    "path": "/api/v1/apps/{clientId}/domains",
    "sourceFile": "apps/[id]/domains/route.ts",
    "excluded": false
  },
  {
    "method": "delete",
    "path": "/api/v1/apps/{clientId}/plans",
    "sourceFile": "apps/[id]/plans/route.ts",
    "excluded": false
  },
  {
    "method": "delete",
    "path": "/api/v1/apps/{clientId}/users",
    "sourceFile": "apps/[id]/users/route.ts",
    "excluded": false
  },
  {
    "method": "delete",
    "path": "/api/v1/apps/{clientId}/users/{externalUserId}/keys",
    "sourceFile": "apps/[id]/users/[externalUserId]/keys/route.ts",
    "excluded": false
  },
  {
    "method": "delete",
    "path": "/api/v1/oidc/{...oidc}",
    "sourceFile": "oidc/[...oidc]/route.ts",
    "excluded": true,
    "excludedReason": "excluded prefix: oidc/"
  },
  {
    "method": "get",
    "path": "/api/v1/admin/apps",
    "sourceFile": "admin/apps/route.ts",
    "excluded": true,
    "excludedReason": "excluded prefix: admin/"
  },
  {
    "method": "get",
    "path": "/api/v1/admin/oidc-clients",
    "sourceFile": "admin/oidc-clients/route.ts",
    "excluded": true,
    "excludedReason": "excluded prefix: admin/"
  },
  {
    "method": "get",
    "path": "/api/v1/apps",
    "sourceFile": "apps/route.ts",
    "excluded": false
  },
  {
    "method": "get",
    "path": "/api/v1/apps/{clientId}",
    "sourceFile": "apps/[id]/route.ts",
    "excluded": false
  },
  {
    "method": "get",
    "path": "/api/v1/apps/{clientId}/admins",
    "sourceFile": "apps/[id]/admins/route.ts",
    "excluded": false
  },
  {
    "method": "get",
    "path": "/api/v1/apps/{clientId}/billing",
    "sourceFile": "apps/[id]/billing/route.ts",
    "excluded": false
  },
  {
    "method": "get",
    "path": "/api/v1/apps/{clientId}/billing/invoices",
    "sourceFile": "apps/[id]/billing/invoices/route.ts",
    "excluded": false
  },
  {
    "method": "get",
    "path": "/api/v1/apps/{clientId}/billing/stripe",
    "sourceFile": "apps/[id]/billing/stripe/route.ts",
    "excluded": false
  },
  {
    "method": "get",
    "path": "/api/v1/apps/{clientId}/billing/stripe/callback",
    "sourceFile": "apps/[id]/billing/stripe/callback/route.ts",
    "excluded": false
  },
  {
    "method": "get",
    "path": "/api/v1/apps/{clientId}/discovery-profiles",
    "sourceFile": "apps/[id]/discovery-profiles/route.ts",
    "excluded": false
  },
  {
    "method": "get",
    "path": "/api/v1/apps/{clientId}/discovery-profiles/{profileId}",
    "sourceFile": "apps/[id]/discovery-profiles/[profileId]/route.ts",
    "excluded": false
  },
  {
    "method": "get",
    "path": "/api/v1/apps/{clientId}/domains",
    "sourceFile": "apps/[id]/domains/route.ts",
    "excluded": false
  },
  {
    "method": "get",
    "path": "/api/v1/apps/{clientId}/manifest",
    "sourceFile": "apps/[id]/manifest/route.ts",
    "excluded": false
  },
  {
    "method": "get",
    "path": "/api/v1/apps/{clientId}/openmeter",
    "sourceFile": "apps/[id]/openmeter/route.ts",
    "excluded": false
  },
  {
    "method": "get",
    "path": "/api/v1/apps/{clientId}/plans",
    "sourceFile": "apps/[id]/plans/route.ts",
    "excluded": false
  },
  {
    "method": "get",
    "path": "/api/v1/apps/{clientId}/signer/routing",
    "sourceFile": "apps/[id]/signer/routing/route.ts",
    "excluded": false
  },
  {
    "method": "get",
    "path": "/api/v1/apps/{clientId}/starter-plan",
    "sourceFile": "apps/[id]/starter-plan/route.ts",
    "excluded": false
  },
  {
    "method": "get",
    "path": "/api/v1/apps/{clientId}/usage",
    "sourceFile": "apps/[id]/usage/route.ts",
    "excluded": false
  },
  {
    "method": "get",
    "path": "/api/v1/apps/{clientId}/usage/balance",
    "sourceFile": "apps/[id]/usage/balance/route.ts",
    "excluded": false
  },
  {
    "method": "get",
    "path": "/api/v1/apps/{clientId}/users",
    "sourceFile": "apps/[id]/users/route.ts",
    "excluded": false
  },
  {
    "method": "get",
    "path": "/api/v1/apps/{clientId}/users/{externalUserId}/allowances",
    "sourceFile": "apps/[id]/users/[externalUserId]/allowances/route.ts",
    "excluded": false
  },
  {
    "method": "get",
    "path": "/api/v1/apps/{clientId}/users/{externalUserId}/keys",
    "sourceFile": "apps/[id]/users/[externalUserId]/keys/route.ts",
    "excluded": false
  },
  {
    "method": "get",
    "path": "/api/v1/apps/{clientId}/users/{externalUserId}/subscription",
    "sourceFile": "apps/[id]/users/[externalUserId]/subscription/route.ts",
    "excluded": false
  },
  {
    "method": "get",
    "path": "/api/v1/apps/branding",
    "sourceFile": "apps/branding/route.ts",
    "excluded": false
  },
  {
    "method": "get",
    "path": "/api/v1/billing",
    "sourceFile": "billing/route.ts",
    "excluded": false
  },
  {
    "method": "get",
    "path": "/api/v1/docs",
    "sourceFile": "docs/route.ts",
    "excluded": true,
    "excludedReason": "meta route (docs or openapi.json)"
  },
  {
    "method": "get",
    "path": "/api/v1/end-users",
    "sourceFile": "end-users/route.ts",
    "excluded": false
  },
  {
    "method": "get",
    "path": "/api/v1/health",
    "sourceFile": "health/route.ts",
    "excluded": false
  },
  {
    "method": "get",
    "path": "/api/v1/marketplace",
    "sourceFile": "marketplace/route.ts",
    "excluded": false
  },
  {
    "method": "get",
    "path": "/api/v1/marketplace/{id}",
    "sourceFile": "marketplace/[id]/route.ts",
    "excluded": false
  },
  {
    "method": "get",
    "path": "/api/v1/oidc/{...oidc}",
    "sourceFile": "oidc/[...oidc]/route.ts",
    "excluded": true,
    "excludedReason": "excluded prefix: oidc/"
  },
  {
    "method": "get",
    "path": "/api/v1/oidc/interaction/{uid}",
    "sourceFile": "oidc/interaction/[uid]/route.ts",
    "excluded": true,
    "excludedReason": "excluded prefix: oidc/"
  },
  {
    "method": "get",
    "path": "/api/v1/openapi.json",
    "sourceFile": "openapi.json/route.ts",
    "excluded": true,
    "excludedReason": "meta route (docs or openapi.json)"
  },
  {
    "method": "get",
    "path": "/api/v1/pipeline-catalog",
    "sourceFile": "pipeline-catalog/route.ts",
    "excluded": false
  },
  {
    "method": "get",
    "path": "/api/v1/pipeline-pricing",
    "sourceFile": "pipeline-pricing/route.ts",
    "excluded": false
  },
  {
    "method": "get",
    "path": "/api/v1/prices/eth-usd",
    "sourceFile": "prices/eth-usd/route.ts",
    "excluded": false
  },
  {
    "method": "get",
    "path": "/api/v1/signer",
    "sourceFile": "signer/route.ts",
    "excluded": false
  },
  {
    "method": "get",
    "path": "/api/v1/signer/cli-status",
    "sourceFile": "signer/cli-status/route.ts",
    "excluded": false
  },
  {
    "method": "get",
    "path": "/api/v1/signer/logs",
    "sourceFile": "signer/logs/route.ts",
    "excluded": false
  },
  {
    "method": "get",
    "path": "/api/v1/subscriptions",
    "sourceFile": "subscriptions/route.ts",
    "excluded": false
  },
  {
    "method": "patch",
    "path": "/api/v1/admin/apps/{id}/marketplace-featured",
    "sourceFile": "admin/apps/[id]/marketplace-featured/route.ts",
    "excluded": true,
    "excludedReason": "excluded prefix: admin/"
  },
  {
    "method": "patch",
    "path": "/api/v1/admin/oidc-clients",
    "sourceFile": "admin/oidc-clients/route.ts",
    "excluded": true,
    "excludedReason": "excluded prefix: admin/"
  },
  {
    "method": "patch",
    "path": "/api/v1/signer",
    "sourceFile": "signer/route.ts",
    "excluded": false
  },
  {
    "method": "post",
    "path": "/api/v1/admin/apps/{id}/review",
    "sourceFile": "admin/apps/[id]/review/route.ts",
    "excluded": true,
    "excludedReason": "excluded prefix: admin/"
  },
  {
    "method": "post",
    "path": "/api/v1/admin/apps/{id}/revoke",
    "sourceFile": "admin/apps/[id]/revoke/route.ts",
    "excluded": true,
    "excludedReason": "excluded prefix: admin/"
  },
  {
    "method": "post",
    "path": "/api/v1/apps",
    "sourceFile": "apps/route.ts",
    "excluded": false
  },
  {
    "method": "post",
    "path": "/api/v1/apps/{clientId}/admins",
    "sourceFile": "apps/[id]/admins/route.ts",
    "excluded": false
  },
  {
    "method": "post",
    "path": "/api/v1/apps/{clientId}/auth/api-key/signer-session",
    "sourceFile": "apps/[id]/auth/api-key/signer-session/route.ts",
    "excluded": false
  },
  {
    "method": "post",
    "path": "/api/v1/apps/{clientId}/auth/api-key/token",
    "sourceFile": "apps/[id]/auth/api-key/token/route.ts",
    "excluded": false
  },
  {
    "method": "post",
    "path": "/api/v1/apps/{clientId}/billing/checkout",
    "sourceFile": "apps/[id]/billing/checkout/route.ts",
    "excluded": false
  },
  {
    "method": "post",
    "path": "/api/v1/apps/{clientId}/billing/stripe/connect",
    "sourceFile": "apps/[id]/billing/stripe/connect/route.ts",
    "excluded": false
  },
  {
    "method": "post",
    "path": "/api/v1/apps/{clientId}/credentials",
    "sourceFile": "apps/[id]/credentials/route.ts",
    "excluded": false
  },
  {
    "method": "post",
    "path": "/api/v1/apps/{clientId}/discovery-profiles",
    "sourceFile": "apps/[id]/discovery-profiles/route.ts",
    "excluded": false
  },
  {
    "method": "post",
    "path": "/api/v1/apps/{clientId}/domains",
    "sourceFile": "apps/[id]/domains/route.ts",
    "excluded": false
  },
  {
    "method": "post",
    "path": "/api/v1/apps/{clientId}/plans",
    "sourceFile": "apps/[id]/plans/route.ts",
    "excluded": false
  },
  {
    "method": "post",
    "path": "/api/v1/apps/{clientId}/plans/{planId}/sync",
    "sourceFile": "apps/[id]/plans/[planId]/sync/route.ts",
    "excluded": false
  },
  {
    "method": "post",
    "path": "/api/v1/apps/{clientId}/publish",
    "sourceFile": "apps/[id]/publish/route.ts",
    "excluded": false
  },
  {
    "method": "post",
    "path": "/api/v1/apps/{clientId}/revert-draft",
    "sourceFile": "apps/[id]/revert-draft/route.ts",
    "excluded": false
  },
  {
    "method": "post",
    "path": "/api/v1/apps/{clientId}/submit",
    "sourceFile": "apps/[id]/submit/route.ts",
    "excluded": false
  },
  {
    "method": "post",
    "path": "/api/v1/apps/{clientId}/usage/signed-tickets",
    "sourceFile": "apps/[id]/usage/signed-tickets/route.ts",
    "excluded": false
  },
  {
    "method": "post",
    "path": "/api/v1/apps/{clientId}/users",
    "sourceFile": "apps/[id]/users/route.ts",
    "excluded": false
  },
  {
    "method": "post",
    "path": "/api/v1/apps/{clientId}/users/{externalUserId}/allowances",
    "sourceFile": "apps/[id]/users/[externalUserId]/allowances/route.ts",
    "excluded": false
  },
  {
    "method": "post",
    "path": "/api/v1/apps/{clientId}/users/{externalUserId}/keys",
    "sourceFile": "apps/[id]/users/[externalUserId]/keys/route.ts",
    "excluded": false
  },
  {
    "method": "post",
    "path": "/api/v1/apps/{clientId}/users/{externalUserId}/token",
    "sourceFile": "apps/[id]/users/[externalUserId]/token/route.ts",
    "excluded": false
  },
  {
    "method": "post",
    "path": "/api/v1/auth/validate",
    "sourceFile": "auth/validate/route.ts",
    "excluded": false
  },
  {
    "method": "post",
    "path": "/api/v1/end-users",
    "sourceFile": "end-users/route.ts",
    "excluded": false
  },
  {
    "method": "post",
    "path": "/api/v1/ingest/events",
    "sourceFile": "ingest/events/route.ts",
    "excluded": false
  },
  {
    "method": "post",
    "path": "/api/v1/internal/ingest/signed-ticket",
    "sourceFile": "internal/ingest/signed-ticket/route.ts",
    "excluded": true,
    "excludedReason": "excluded prefix: internal/"
  },
  {
    "method": "post",
    "path": "/api/v1/oidc/{...oidc}",
    "sourceFile": "oidc/[...oidc]/route.ts",
    "excluded": true,
    "excludedReason": "excluded prefix: oidc/"
  },
  {
    "method": "post",
    "path": "/api/v1/oidc/device/verify",
    "sourceFile": "oidc/device/verify/route.ts",
    "excluded": true,
    "excludedReason": "excluded prefix: oidc/"
  },
  {
    "method": "post",
    "path": "/api/v1/oidc/interaction/{uid}",
    "sourceFile": "oidc/interaction/[uid]/route.ts",
    "excluded": true,
    "excludedReason": "excluded prefix: oidc/"
  },
  {
    "method": "post",
    "path": "/api/v1/signer/control",
    "sourceFile": "signer/control/route.ts",
    "excluded": false
  },
  {
    "method": "put",
    "path": "/api/v1/apps/{clientId}",
    "sourceFile": "apps/[id]/route.ts",
    "excluded": false
  },
  {
    "method": "put",
    "path": "/api/v1/apps/{clientId}/discovery-profiles/{profileId}",
    "sourceFile": "apps/[id]/discovery-profiles/[profileId]/route.ts",
    "excluded": false
  },
  {
    "method": "put",
    "path": "/api/v1/apps/{clientId}/manifest",
    "sourceFile": "apps/[id]/manifest/route.ts",
    "excluded": false
  },
  {
    "method": "put",
    "path": "/api/v1/apps/{clientId}/openmeter",
    "sourceFile": "apps/[id]/openmeter/route.ts",
    "excluded": false
  },
  {
    "method": "put",
    "path": "/api/v1/apps/{clientId}/plans",
    "sourceFile": "apps/[id]/plans/route.ts",
    "excluded": false
  },
  {
    "method": "put",
    "path": "/api/v1/apps/{clientId}/settings",
    "sourceFile": "apps/[id]/settings/route.ts",
    "excluded": false
  },
  {
    "method": "put",
    "path": "/api/v1/apps/{clientId}/starter-plan",
    "sourceFile": "apps/[id]/starter-plan/route.ts",
    "excluded": false
  },
  {
    "method": "put",
    "path": "/api/v1/apps/{clientId}/users",
    "sourceFile": "apps/[id]/users/route.ts",
    "excluded": false
  },
  {
    "method": "put",
    "path": "/api/v1/oidc/{...oidc}",
    "sourceFile": "oidc/[...oidc]/route.ts",
    "excluded": true,
    "excludedReason": "excluded prefix: oidc/"
  }
] as const;

export const OPENAPI_PUBLIC_ROUTE_KEYS: readonly string[] = [
  "DELETE /api/v1/apps/{clientId}",
  "DELETE /api/v1/apps/{clientId}/admins",
  "DELETE /api/v1/apps/{clientId}/billing/stripe",
  "DELETE /api/v1/apps/{clientId}/discovery-profiles/{profileId}",
  "DELETE /api/v1/apps/{clientId}/domains",
  "DELETE /api/v1/apps/{clientId}/plans",
  "DELETE /api/v1/apps/{clientId}/users",
  "DELETE /api/v1/apps/{clientId}/users/{externalUserId}/keys",
  "GET /api/v1/apps",
  "GET /api/v1/apps/{clientId}",
  "GET /api/v1/apps/{clientId}/admins",
  "GET /api/v1/apps/{clientId}/billing",
  "GET /api/v1/apps/{clientId}/billing/invoices",
  "GET /api/v1/apps/{clientId}/billing/stripe",
  "GET /api/v1/apps/{clientId}/billing/stripe/callback",
  "GET /api/v1/apps/{clientId}/discovery-profiles",
  "GET /api/v1/apps/{clientId}/discovery-profiles/{profileId}",
  "GET /api/v1/apps/{clientId}/domains",
  "GET /api/v1/apps/{clientId}/manifest",
  "GET /api/v1/apps/{clientId}/openmeter",
  "GET /api/v1/apps/{clientId}/plans",
  "GET /api/v1/apps/{clientId}/signer/routing",
  "GET /api/v1/apps/{clientId}/starter-plan",
  "GET /api/v1/apps/{clientId}/usage",
  "GET /api/v1/apps/{clientId}/usage/balance",
  "GET /api/v1/apps/{clientId}/users",
  "GET /api/v1/apps/{clientId}/users/{externalUserId}/allowances",
  "GET /api/v1/apps/{clientId}/users/{externalUserId}/keys",
  "GET /api/v1/apps/{clientId}/users/{externalUserId}/subscription",
  "GET /api/v1/apps/branding",
  "GET /api/v1/billing",
  "GET /api/v1/end-users",
  "GET /api/v1/health",
  "GET /api/v1/marketplace",
  "GET /api/v1/marketplace/{id}",
  "GET /api/v1/pipeline-catalog",
  "GET /api/v1/pipeline-pricing",
  "GET /api/v1/prices/eth-usd",
  "GET /api/v1/signer",
  "GET /api/v1/signer/cli-status",
  "GET /api/v1/signer/logs",
  "GET /api/v1/subscriptions",
  "PATCH /api/v1/signer",
  "POST /api/v1/apps",
  "POST /api/v1/apps/{clientId}/admins",
  "POST /api/v1/apps/{clientId}/auth/api-key/signer-session",
  "POST /api/v1/apps/{clientId}/auth/api-key/token",
  "POST /api/v1/apps/{clientId}/billing/checkout",
  "POST /api/v1/apps/{clientId}/billing/stripe/connect",
  "POST /api/v1/apps/{clientId}/credentials",
  "POST /api/v1/apps/{clientId}/discovery-profiles",
  "POST /api/v1/apps/{clientId}/domains",
  "POST /api/v1/apps/{clientId}/plans",
  "POST /api/v1/apps/{clientId}/plans/{planId}/sync",
  "POST /api/v1/apps/{clientId}/publish",
  "POST /api/v1/apps/{clientId}/revert-draft",
  "POST /api/v1/apps/{clientId}/submit",
  "POST /api/v1/apps/{clientId}/usage/signed-tickets",
  "POST /api/v1/apps/{clientId}/users",
  "POST /api/v1/apps/{clientId}/users/{externalUserId}/allowances",
  "POST /api/v1/apps/{clientId}/users/{externalUserId}/keys",
  "POST /api/v1/apps/{clientId}/users/{externalUserId}/token",
  "POST /api/v1/auth/validate",
  "POST /api/v1/end-users",
  "POST /api/v1/ingest/events",
  "POST /api/v1/signer/control",
  "PUT /api/v1/apps/{clientId}",
  "PUT /api/v1/apps/{clientId}/discovery-profiles/{profileId}",
  "PUT /api/v1/apps/{clientId}/manifest",
  "PUT /api/v1/apps/{clientId}/openmeter",
  "PUT /api/v1/apps/{clientId}/plans",
  "PUT /api/v1/apps/{clientId}/settings",
  "PUT /api/v1/apps/{clientId}/starter-plan",
  "PUT /api/v1/apps/{clientId}/users"
] as const;

export const OPENAPI_PUBLIC_ROUTE_COUNT = 74;
