import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, rmSync, statSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";

import {
  CUSTOMER_SERVICE_OIDC_ENV_FILENAME,
  formatCustomerServiceOidcEnv,
  writeCustomerServiceOidcEnvFile,
} from "@/lib/oidc/customer-service-oidc-env";

const sample = {
  issuer: "http://localhost:3001/api/v1/oidc",
  apiBaseUrl: "http://localhost:3001",
  clientId: "web_customer_service",
  clientSecret: "pmth_cs_test_secret",
  redirectUri: "http://localhost:3010/api/auth/callback/pymthouse",
};

test("formatCustomerServiceOidcEnv is a copy-paste snippet without extra keys", () => {
  const body = formatCustomerServiceOidcEnv(sample);
  assert.match(body, /^# Generated by npm run bootstrap/m);
  assert.match(body, /^PYMTHOUSE_ISSUER=http:\/\/localhost:3001\/api\/v1\/oidc$/m);
  assert.match(body, /^CS_OIDC_CLIENT_SECRET=pmth_cs_test_secret$/m);
  assert.equal(CUSTOMER_SERVICE_OIDC_ENV_FILENAME, ".env.customer-service-oidc");
});

test("writeCustomerServiceOidcEnvFile writes mode 0600", () => {
  const dir = mkdtempSync(join(tmpdir(), "cs-oidc-env-"));
  const filePath = join(dir, CUSTOMER_SERVICE_OIDC_ENV_FILENAME);
  try {
    writeCustomerServiceOidcEnvFile(filePath, sample);
    const mode = statSync(filePath).mode & 0o777;
    assert.equal(mode, 0o600);
    assert.equal(readFileSync(filePath, "utf8"), formatCustomerServiceOidcEnv(sample));
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});
