import { chmodSync, writeFileSync } from "node:fs";

/** Gitignored snippet (`/.env*`). Bootstrap writes the CS client secret here, not stdout. */
export const CUSTOMER_SERVICE_OIDC_ENV_FILENAME = ".env.customer-service-oidc";

export function formatCustomerServiceOidcEnv(params: {
  issuer: string;
  apiBaseUrl: string;
  clientId: string;
  clientSecret: string;
  redirectUri: string;
}): string {
  return [
    "# Generated by npm run bootstrap. Copy into customer-service .env — do not commit.",
    `PYMTHOUSE_ISSUER=${params.issuer}`,
    `PYMTHOUSE_API_BASE_URL=${params.apiBaseUrl}`,
    `CS_OIDC_CLIENT_ID=${params.clientId}`,
    `CS_OIDC_CLIENT_SECRET=${params.clientSecret}`,
    `CS_OIDC_REDIRECT_URI=${params.redirectUri}`,
    "",
  ].join("\n");
}

export function writeCustomerServiceOidcEnvFile(
  filePath: string,
  params: {
    issuer: string;
    apiBaseUrl: string;
    clientId: string;
    clientSecret: string;
    redirectUri: string;
  },
): void {
  writeFileSync(filePath, formatCustomerServiceOidcEnv(params), {
    encoding: "utf8",
    mode: 0o600,
  });
  chmodSync(filePath, 0o600);
}
