#!/usr/bin/env npx tsx
/**
 * Regenerate OpenAPI route inventory from src/app/api/v1 route handlers.
 * Run via: npm run openapi:generate
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";

import {
  publicRouteOperations,
  scanApiV1Routes,
  type ScannedRouteOperation,
} from "../src/lib/openapi/route-scan";

const OUTPUT = join(process.cwd(), "src/lib/openapi/generated-route-inventory.ts");

function formatInventoryLine(op: ScannedRouteOperation): string {
  const args = [
    JSON.stringify(op.method),
    JSON.stringify(op.path),
    JSON.stringify(op.sourceFile),
  ];
  if (op.excluded) {
    args.push("true");
    if (op.excludedReason) {
      args.push(JSON.stringify(op.excludedReason));
    }
  }
  return `  inventoryOp(${args.join(", ")}),`;
}

function main() {
  const scanned = scanApiV1Routes();
  const publicOps = publicRouteOperations(scanned);
  const inventoryLines = scanned.map(formatInventoryLine).join("\n");

  const body = `/**
 * AUTO-GENERATED by scripts/generate-openapi-routes.ts — do not edit by hand.
 * Regenerate: npm run openapi:generate
 */
import { inventoryOp } from "@/lib/openapi/route-scan";
import type { ScannedRouteOperation } from "@/lib/openapi/route-scan";

export const OPENAPI_ROUTE_INVENTORY: ScannedRouteOperation[] = [
${inventoryLines}
];

export const OPENAPI_PUBLIC_ROUTE_KEYS: readonly string[] = ${JSON.stringify(
    publicOps.map((op) => `${op.method.toUpperCase()} ${op.path}`),
  )};

export const OPENAPI_PUBLIC_ROUTE_COUNT = ${publicOps.length};
`;

  writeFileSync(OUTPUT, body, "utf8");
  console.log(
    `Wrote ${OUTPUT} (${scanned.length} total operations, ${publicOps.length} public).`,
  );
}

main();
