#!/usr/bin/env npx tsx
/**
 * Regenerate OpenAPI route inventory from src/app/api/v1 route handlers.
 * Run via: npm run openapi:generate
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";

import {
  publicRouteOperations,
  scanApiV1Routes,
} from "../src/lib/openapi/route-scan";

const OUTPUT = join(process.cwd(), "src/lib/openapi/generated-route-inventory.ts");

function main() {
  const scanned = scanApiV1Routes();
  const publicOps = publicRouteOperations(scanned);

  const body = `/**
 * AUTO-GENERATED by scripts/generate-openapi-routes.ts — do not edit by hand.
 * Regenerate: npm run openapi:generate
 */
import type { ScannedRouteOperation } from "@/lib/openapi/route-scan";

export const OPENAPI_ROUTE_INVENTORY: ScannedRouteOperation[] = ${JSON.stringify(scanned, null, 2)} as const;

export const OPENAPI_PUBLIC_ROUTE_KEYS: readonly string[] = ${JSON.stringify(
    publicOps.map((op) => `${op.method.toUpperCase()} ${op.path}`),
    null,
    2,
  )} as const;

export const OPENAPI_PUBLIC_ROUTE_COUNT = ${publicOps.length};
`;

  writeFileSync(OUTPUT, body, "utf8");
  console.log(
    `Wrote ${OUTPUT} (${scanned.length} total operations, ${publicOps.length} public).`,
  );
}

main();
