name: SonarQube Cloud analysis

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube Cloud
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout pymthouse
        uses: actions/checkout@v4
        with:
          # Shallow clones should be disabled for a better relevancy of analysis
          fetch-depth: 0

      - name: SonarQube Cloud scan
        uses: SonarSource/sonarqube-scan-action@2f77a1ec69fb1d595b06f35ab27e97605bdef703 # v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
